# Generated by Django 6.1.1 on 2026-09-18 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_banner'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(verbose_name='Лет в небе')),
                ('naprav', models.IntegerField(verbose_name='Направлений')),
                ('people', models.IntegerField(verbose_name='Пассажиров в год')),
                ('rais', models.IntegerField(verbose_name='Рейсов в небе')),
            ],
            options={
                'verbose_name': 'Мы в числах',
                'verbose_name_plural': 'Мы в числах',
            },
        ),
    ]
